import io.zengin4j.core.codec.ReaderOptions;
import io.zengin4j.core.codec.ZenginReader;
import io.zengin4j.core.codec.ZenginReaders;
import io.zengin4j.core.codec.RecordView;
import io.zengin4j.core.format.FormatRegistry;
import io.zengin4j.core.format.RecordKind;
import io.zengin4j.core.model.Batch;
import io.zengin4j.core.model.DataRecord;
import io.zengin4j.core.model.ZenginFile;
import io.zengin4j.core.model.generated.SougouFurikomiData;
import io.zengin4j.core.time.MonthDayResolver;
import io.zengin4j.testkit.SougouFurikomiFixtures;

/// UC-2: read a 総合振込 file into a downstream pipeline.
///
/// Run it with:
///
/// ```
/// ./gradlew runExamples
/// ```
///
/// The file it reads is generated by the testkit, so the example needs no
/// input of its own — and so that nothing resembling real payment data is
/// committed to this repository (R-L1, P1).
void main() {
    SougouFurikomiFixtures fixtures = SougouFurikomiFixtures.create();
    byte[] file = fixtures.file(3, io.zengin4j.core.model.SeparatorStyle.CRLF, false);

    // Build the registry once. It is immutable and thread-safe, and
    // ReaderOptions.defaults() would otherwise reload it on every call.
    FormatRegistry registry = FormatRegistry.defaults();

    ReaderOptions options = ReaderOptions.builder()
            .registry(registry)
            // Every descriptor in 0.1.0 is verified: false. Without this the
            // reader refuses to guess at a provisional byte layout. Read
            // DISCLAIMER.md before setting it against a real file.
            .allowUnverifiedFormats(true)
            .warningListener(warning -> System.out.println("[warn] " + warning.messageEn()))
            .build();

    wholeFile(file, options);
    streaming(file, options);
}

/// The convenient API: everything materialised, nothing to remember.
private static void wholeFile(byte[] file, ReaderOptions options) {
    System.out.println("== whole file ==");
    ZenginFile parsed = ZenginReaders.readFile(new ByteArrayInputStream(file), options);

    // MMDD carries no year. Attaching one is an explicit, named decision:
    // FORWARD_LOOKING is right for instruction files, NEAREST for results.
    MonthDayResolver resolver = MonthDayResolver.forwardLooking(LocalDate.now());

    for (Batch batch : parsed.batches()) {
        String valueDate = batch.header().effectiveDate()
                .map(monthDay -> resolver.resolve(monthDay).explain())
                .orElse("no value date");

        System.out.printf("%s — %d payments, ¥%,d total%n  %s%n",
                batch.header().originatorName(),
                batch.computedCount(),
                batch.computedTotal(),
                valueDate);

        for (DataRecord record : batch.data()) {
            // The record is format-shaped: exactly the fields 総合振込 has.
            SougouFurikomiData payment = (SougouFurikomiData) record;
            System.out.printf("    %-20s %s/%s  ¥%,d%n",
                    payment.beneficiaryName(),
                    payment.beneficiaryBankCode(),
                    payment.beneficiaryBranchCode(),
                    payment.amount());
        }
    }

    // What the trailer claims, against what the records actually contain.
    // Reconciling the two is the validation layer's job (Epic 4); core just
    // gives you both numbers.
    parsed.batches().forEach(batch -> batch.trailer().ifPresent(trailer ->
            System.out.printf("  trailer says %d records / ¥%,d; records add up to %d / ¥%,d%n",
                    trailer.recordCount(), trailer.totalAmount(),
                    batch.computedCount(), batch.computedTotal())));
}

/// The fast API: constant memory, nothing decoded until asked for.
private static void streaming(byte[] file, ReaderOptions options) {
    System.out.println("== streaming ==");
    long total = 0;
    int payments = 0;

    try (ZenginReader reader = ZenginReaders.open(new ByteArrayInputStream(file), options)) {
        while (reader.hasNext()) {
            RecordView view = reader.next();
            if (view.kind() == RecordKind.DATA) {
                // Decodes straight from the buffer: no String, no boxing.
                total += view.asLong(view.field("amount"));
                payments++;
            }
            // NOTE: `view` is a window onto a recycled buffer and stops being
            // valid at the next next(). Call view.materialize() to keep one.
        }
    }

    System.out.printf("%d payments, ¥%,d total%n", payments, total);
}
