package io.zengin4j.codegen;

import io.zengin4j.core.format.CodeList;
import io.zengin4j.core.format.CodeValue;
import io.zengin4j.core.format.FieldDescriptor;
import io.zengin4j.core.format.FormatDescriptor;
import io.zengin4j.core.format.RecordDescriptor;
import io.zengin4j.core.format.RecordKind;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

/**
 * Emits the bundled descriptors into {@code zengin4j-core} as committed Java.
 *
 * <p>This is what lets core ship with no descriptor parser and no descriptor
 * resources: the YAML is a build input, not a runtime artifact (ADR-0016).
 *
 * <p>The generated code never writes a byte offset. It lists each field's
 * length in layout order and lets {@link RecordDescriptor#of} compute the
 * offsets, exactly as the file reader used to (R-F2) — so the guarantee
 * survives the move rather than being reimplemented in the generator.
 */
final class BundledFormatsGenerator {

    static final String PACKAGE = "io.zengin4j.core.format.generated";
    static final String GENERATOR = "io.zengin4j.codegen.BundledFormatsGenerator";

    private static final String NL = "\n";

    private final Path javaRoot;

    BundledFormatsGenerator(Path javaRoot) {
        this.javaRoot = javaRoot;
    }

    GeneratedFile generate(
            Map<String, CodeList> codeLists,
            List<FormatDescriptor> formats,
            Map<FormatDescriptor, String> sources) {

        StringBuilder out = new StringBuilder();
        out.append("package ").append(PACKAGE).append(';').append(NL).append(NL)
                .append("import io.zengin4j.core.annotation.Generated;").append(NL)
                .append("import io.zengin4j.core.format.CodeList;").append(NL)
                .append("import io.zengin4j.core.format.CodeValue;").append(NL)
                .append("import io.zengin4j.core.format.FieldFormat;").append(NL)
                .append("import io.zengin4j.core.format.FieldSpec;").append(NL)
                .append("import io.zengin4j.core.format.FieldType;").append(NL)
                .append("import io.zengin4j.core.format.FormatDescriptor;").append(NL)
                .append("import io.zengin4j.core.format.FormatId;").append(NL)
                .append("import io.zengin4j.core.format.RecordDescriptor;").append(NL)
                .append("import io.zengin4j.core.format.RecordKind;").append(NL)
                .append("import java.util.Collections;").append(NL)
                .append("import java.util.EnumMap;").append(NL)
                .append("import java.util.LinkedHashMap;").append(NL)
                .append("import java.util.List;").append(NL)
                .append("import java.util.Map;").append(NL)
                .append("import java.util.Optional;").append(NL).append(NL);

        out.append("/**").append(NL)
                .append(" * The format descriptors bundled with this library.").append(NL)
                .append(" *").append(NL)
                .append(" * <p>GENERATED by ").append(GENERATOR).append(" from the descriptor sources in")
                .append(NL)
                .append(" * {@code zengin4j-core/formats} — do not edit.").append(NL)
                .append(" *").append(NL)
                .append(" * <p>The descriptors are authored as YAML and compiled to Java by the build,")
                .append(NL)
                .append(" * so that {@code zengin4j-core} needs neither a YAML parser nor descriptor")
                .append(NL)
                .append(" * resources at runtime (R-M1, ADR-0016). Byte offsets are computed by")
                .append(NL)
                .append(" * {@link RecordDescriptor#of} from the field lengths below, never written")
                .append(NL)
                .append(" * out (R-F2).").append(NL)
                .append(" *").append(NL)
                .append(" * @since 0.1.0").append(NL)
                .append(" */").append(NL)
                .append("@Generated(value = \"").append(GENERATOR).append("\", source = \"formats/*.yaml\")")
                .append(NL)
                .append("public final class BundledFormats {").append(NL).append(NL)
                .append("    private BundledFormats() {").append(NL)
                .append("    }").append(NL).append(NL);

        codeListsAccessor(out, codeLists);
        formatsAccessor(out, formats);

        for (CodeList list : codeLists.values()) {
            codeListMethod(out, list);
        }
        for (FormatDescriptor format : formats) {
            formatMethod(out, format, sources.get(format));
        }

        out.append('}').append(NL);

        Path path = javaRoot;
        for (String part : PACKAGE.split("\\.")) {
            path = path.resolve(part);
        }
        return new GeneratedFile(path.resolve("BundledFormats.java"), out.toString());
    }

    GeneratedFile packageInfo() {
        String content = "/**" + NL
                + " * Descriptors compiled from their YAML sources by the build (ADR-0016)." + NL
                + " *" + NL
                + " * <p>GENERATED and committed, never hand-edited (R-M8). Editing a byte layout" + NL
                + " * means editing the descriptor it comes from and regenerating; the build fails" + NL
                + " * if the committed output has drifted." + NL
                + " *" + NL
                + " * @since 0.1.0" + NL
                + " */" + NL
                + "package " + PACKAGE + ";" + NL;
        Path path = javaRoot;
        for (String part : PACKAGE.split("\\.")) {
            path = path.resolve(part);
        }
        return new GeneratedFile(path.resolve("package-info.java"), content);
    }

    // ------------------------------------------------------------- accessors

    private void codeListsAccessor(StringBuilder out, Map<String, CodeList> codeLists) {
        out.append("    /**").append(NL)
                .append("     * Returns the code lists the bundled descriptors reference.").append(NL)
                .append("     *").append(NL)
                .append("     * @return a new unmodifiable map, keyed by code list id").append(NL)
                .append("     */").append(NL)
                .append("    public static Map<String, CodeList> codeLists() {").append(NL)
                .append("        Map<String, CodeList> lists = new LinkedHashMap<>();").append(NL);
        for (CodeList list : codeLists.values()) {
            out.append("        lists.put(").append(quote(list.id())).append(", ")
                    .append(methodName(list.id())).append("());").append(NL);
        }
        out.append("        return Collections.unmodifiableMap(lists);").append(NL)
                .append("    }").append(NL).append(NL);
    }

    private void formatsAccessor(StringBuilder out, List<FormatDescriptor> formats) {
        out.append("    /**").append(NL)
                .append("     * Returns the bundled format descriptors.").append(NL)
                .append("     *").append(NL)
                .append("     * @param codeLists the code lists to resolve references against,")
                .append(NL)
                .append("     *                  normally {@link #codeLists()}").append(NL)
                .append("     * @return the descriptors, in a stable order").append(NL)
                .append("     */").append(NL)
                .append("    public static List<FormatDescriptor> formats(Map<String, CodeList> codeLists) {")
                .append(NL)
                .append("        return List.of(");
        for (int i = 0; i < formats.size(); i++) {
            out.append(methodName(formats.get(i).id().value())).append("(codeLists)")
                    .append(i == formats.size() - 1 ? "" : ", ");
        }
        out.append(");").append(NL)
                .append("    }").append(NL).append(NL);
    }

    // ---------------------------------------------------------------- bodies

    private void codeListMethod(StringBuilder out, CodeList list) {
        out.append("    private static CodeList ").append(methodName(list.id())).append("() {").append(NL)
                .append("        return new CodeList(").append(NL)
                .append("                ").append(quote(list.id())).append(',').append(NL)
                .append("                ").append(quote(list.nameJa())).append(',').append(NL)
                .append("                ").append(quote(list.nameEn())).append(',').append(NL)
                .append("                ").append(list.verified()).append(',').append(NL)
                .append("                ").append(list.open()).append(',').append(NL);
        if (list.values().isEmpty()) {
            out.append("                List.of(),").append(NL);
        } else {
            out.append("                List.of(").append(NL);
            for (int i = 0; i < list.values().size(); i++) {
                CodeValue value = list.values().get(i);
                out.append("                        new CodeValue(")
                        .append(quote(value.code())).append(", ")
                        .append(quote(value.nameJa())).append(", ")
                        .append(quote(value.nameEn())).append(", ")
                        .append(value.verified()).append(", ")
                        .append(optional(value.note())).append(')')
                        .append(i == list.values().size() - 1 ? "),": ",").append(NL);
            }
        }
        out.append("                ").append(stringList(list.sources())).append(',').append(NL)
                .append("                ").append(optional(list.note())).append(");").append(NL)
                .append("    }").append(NL).append(NL);
    }

    private void formatMethod(StringBuilder out, FormatDescriptor format, String source) {
        String method = methodName(format.id().value());
        out.append("    /** ").append(format.nameJa()).append(" — from ").append(source).append(". */")
                .append(NL)
                .append("    private static FormatDescriptor ").append(method)
                .append("(Map<String, CodeList> codeLists) {").append(NL)
                .append("        FormatId id = FormatId.of(").append(quote(format.id().value())).append(");")
                .append(NL)
                .append("        Map<RecordKind, RecordDescriptor> records = new EnumMap<>(RecordKind.class);")
                .append(NL);
        for (RecordKind kind : List.of(RecordKind.HEADER, RecordKind.DATA, RecordKind.TRAILER, RecordKind.END)) {
            format.find(kind).ifPresent(record -> out.append("        records.put(RecordKind.").append(kind)
                    .append(", ").append(method).append(kind.descriptorKey().substring(0, 1).toUpperCase(Locale.ROOT))
                    .append(kind.descriptorKey().substring(1)).append("(id, codeLists));").append(NL));
        }
        out.append("        return new FormatDescriptor(").append(NL)
                .append("                id,").append(NL)
                .append("                ").append(quote(format.nameJa())).append(',').append(NL)
                .append("                ").append(quote(format.nameEn())).append(',').append(NL)
                .append("                ").append(quote(format.typeCode())).append(',').append(NL)
                .append("                ").append(format.recordLength()).append(',').append(NL)
                .append("                ").append(format.verified()).append(',').append(NL)
                .append("                ").append(stringList(format.sources())).append(',').append(NL)
                .append("                ").append(optional(format.note())).append(',').append(NL)
                .append("                records);").append(NL)
                .append("    }").append(NL).append(NL);

        for (RecordKind kind : List.of(RecordKind.HEADER, RecordKind.DATA, RecordKind.TRAILER, RecordKind.END)) {
            format.find(kind).ifPresent(record -> recordMethod(out, method, record));
        }
    }

    private void recordMethod(StringBuilder out, String formatMethod, RecordDescriptor record) {
        String key = record.kind().descriptorKey();
        out.append("    private static RecordDescriptor ").append(formatMethod)
                .append(key.substring(0, 1).toUpperCase(Locale.ROOT)).append(key.substring(1))
                .append("(FormatId id, Map<String, CodeList> codeLists) {").append(NL)
                .append("        return RecordDescriptor.of(id, RecordKind.").append(record.kind())
                .append(", (byte) '").append((char) record.discriminator()).append("', ")
                .append(record.recordLength()).append(", List.of(").append(NL);
        List<FieldDescriptor> fields = record.fields();
        for (int i = 0; i < fields.size(); i++) {
            FieldDescriptor field = fields.get(i);
            out.append("                FieldSpec.of(").append(field.sequence()).append(", ")
                    .append(quote(field.id())).append(", ")
                    .append(quote(field.nameJa())).append(", ")
                    .append(quote(field.nameEn())).append(", FieldType.").append(field.type())
                    .append(", ").append(field.length()).append(')');
            if (field.required()) {
                out.append(".withRequired()");
            }
            if (field.filler()) {
                out.append(".withFiller()");
            }
            if (field.sensitive()) {
                out.append(".withSensitive()");
            }
            field.format().ifPresent(value ->
                    out.append(".withFormat(FieldFormat.").append(value.name()).append(')'));
            field.constant().ifPresent(value ->
                    out.append(".withConstant(").append(quote(value)).append(')'));
            field.codeList().ifPresent(value ->
                    out.append(".withCodeList(codeLists.get(").append(quote(value.id())).append("))"));
            field.note().ifPresent(value ->
                    out.append(".withNote(").append(quote(value)).append(')'));
            out.append(i == fields.size() - 1 ? "));" : ",").append(NL);
        }
        out.append("    }").append(NL).append(NL);
    }

    // --------------------------------------------------------------- helpers

    private static String methodName(String id) {
        StringBuilder result = new StringBuilder();
        boolean capitalise = false;
        for (int i = 0; i < id.length(); i++) {
            char c = id.charAt(i);
            if (c == '-') {
                capitalise = true;
                continue;
            }
            result.append(capitalise ? Character.toUpperCase(c) : c);
            capitalise = false;
        }
        return result.toString();
    }

    private static String stringList(List<String> values) {
        if (values.isEmpty()) {
            return "List.of()";
        }
        StringBuilder out = new StringBuilder("List.of(").append(NL);
        for (int i = 0; i < values.size(); i++) {
            out.append("                        ").append(quote(values.get(i)))
                    .append(i == values.size() - 1 ? ")" : ",").append(NL);
        }
        return out.append("                ").toString().stripTrailing();
    }

    private static String optional(Optional<String> value) {
        return value.map(text -> "Optional.of(" + quote(text) + ")").orElse("Optional.empty()");
    }

    private static String quote(String value) {
        StringBuilder out = new StringBuilder("\"");
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> out.append(c);
            }
        }
        return out.append('"').toString();
    }
}
