package io.zengin4j.codegen;

import module java.base;

/// Compiles the declared mappings into Java.
///
/// The rows become a constant table in `zengin4j-iso20022`, so the
/// mapper reads its own declaration without a YAML parser at runtime and a test
/// can compare what the mapper actually emits against what the declaration says
/// it should.
final class MappingSourceGenerator {

    private static final String PACKAGE = "io.zengin4j.iso20022.mapping.generated";
    private static final String CLASS = "BundledMappings";
    private static final String NL = "\n";

    private final Path javaOut;

    MappingSourceGenerator(Path javaOut) {
        this.javaOut = javaOut;
    }

    /// Generates the table.
    ///
    /// @param mappings the declarations, in file-name order
    /// @param sources  each declaration's file name, for the `@Generated`
    ///   annotation
    /// @return the generated file
    GeneratedFile generate(List<MappingReader.Mapping> mappings, List<String> sources) {
        StringBuilder out = new StringBuilder();
        out.append("package ").append(PACKAGE).append(';').append(NL).append(NL)
                .append("import module java.base;").append(NL)
                .append("import io.zengin4j.core.annotation.Generated;").append(NL)
                .append("import io.zengin4j.core.format.FormatId;").append(NL)
                .append("import io.zengin4j.core.loss.LossKind;").append(NL)
                .append("import io.zengin4j.core.loss.LossSeverity;").append(NL)
                .append("import io.zengin4j.iso20022.envelope.MessageId;").append(NL)
                .append("import io.zengin4j.iso20022.mapping.MappingDirection;").append(NL)
                .append("import io.zengin4j.iso20022.mapping.MappingRow;").append(NL).append(NL);

        out.append("/// The mapping rows this library ships.").append(NL)
                .append("///").append(NL)
                .append("/// GENERATED by io.zengin4j.codegen.MappingSourceGenerator from ")
                .append(String.join(", ", sources)).append(" — do not edit.").append(NL)
                .append("///").append(NL)
                .append("/// **Every row is unverified.** R-I19 permits a row to be")
                .append(NL)
                .append("/// marked conformant only once it has been checked against published")
                .append(NL)
                .append("/// profile documentation, and none has been.").append(NL)
                .append("///").append(NL)
                .append("/// @since 0.5.0").append(NL)
                .append("@Generated(value = \"io.zengin4j.codegen.MappingSourceGenerator\",")
                .append(" source = \"").append(String.join(", ", sources)).append("\")").append(NL)
                .append("public final class ").append(CLASS).append(" {").append(NL).append(NL);

        for (MappingReader.Mapping mapping : mappings) {
            appendMapping(out, mapping);
        }

        out.append("    /// Every bundled mapping, keyed by format and message.").append(NL)
                .append("    public static final Map<String, List<MappingRow>> ALL = Map.of(")
                .append(NL);
        for (int i = 0; i < mappings.size(); i++) {
            MappingReader.Mapping mapping = mappings.get(i);
            out.append("            key(FormatId.of(\"").append(mapping.format())
                    .append("\"), new MessageId(\"").append(mapping.message()).append("\")), ")
                    .append(constant(mapping)).append(i + 1 < mappings.size() ? "," : "")
                    .append(NL);
        }
        out.append("    );").append(NL).append(NL);

        out.append("    private ").append(CLASS).append("() {").append(NL)
                .append("    }").append(NL).append(NL)
                .append("    /// The key a mapping is stored under.").append(NL)
                .append("    ///").append(NL)
                .append("    /// @param format  the Zengin format").append(NL)
                .append("    /// @param message the ISO 20022 message").append(NL)
                .append("    /// @return the key").append(NL)
                .append("    public static String key(FormatId format, MessageId message) {")
                .append(NL)
                .append("        return format.value() + \" <-> \" + message.value();").append(NL)
                .append("    }").append(NL)
                .append("}").append(NL);

        return new GeneratedFile(
                javaOut.resolve(PACKAGE.replace('.', '/')).resolve(CLASS + ".java"),
                out.toString());
    }

    private void appendMapping(StringBuilder out, MappingReader.Mapping mapping) {
        out.append("    /// ").append(mapping.format()).append(" &lt;-&gt; ")
                .append(mapping.message()).append(", ").append(mapping.rows().size())
                .append(" rows.").append(NL)
                .append("    public static final List<MappingRow> ").append(constant(mapping))
                .append(" = List.of(").append(NL);

        for (int i = 0; i < mapping.rows().size(); i++) {
            MappingReader.Row row = mapping.rows().get(i);
            out.append("            new MappingRow(").append(NL)
                    .append("                    ").append(quote(row.zenginField())).append(',')
                    .append(NL)
                    .append("                    ").append(quote(row.isoPath())).append(',')
                    .append(NL)
                    .append("                    MappingDirection.")
                    .append(row.direction().toUpperCase(java.util.Locale.ROOT).replace('-', '_'))
                    .append(',').append(NL)
                    .append("                    ").append(row.verified()).append(',').append(NL)
                    .append("                    ").append(row.lossKind().isEmpty()
                            ? "Optional.empty()"
                            : "Optional.of(LossKind." + row.lossKind() + ")").append(',').append(NL)
                    .append("                    ").append(row.lossSeverity().isEmpty()
                            ? "Optional.empty()"
                            : "Optional.of(LossSeverity." + row.lossSeverity() + ")").append(',')
                    .append(NL)
                    .append("                    ").append(quote(row.whyEn())).append(',')
                    .append(NL)
                    .append("                    ").append(quote(row.whyJa())).append(')')
                    .append(i + 1 < mapping.rows().size() ? "," : "").append(NL);
        }
        out.append("    );").append(NL).append(NL);
    }

    private static String constant(MappingReader.Mapping mapping) {
        return mapping.id().toUpperCase(java.util.Locale.ROOT).replace('-', '_');
    }

    /// Java string literals, ASCII-escaped.
    ///
    /// The explanations are half Japanese. Escaping them means the generated
    /// source compiles the same way whatever a build machine's default encoding
    /// is, which is the same reason the kana tables are escaped.
    private static String quote(String value) {
        StringBuilder out = new StringBuilder(value.length() + 2).append('"');
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                default -> {
                    if (c < 0x20 || c > 0x7E) {
                        out.append(String.format("\\u%04x", (int) c));
                    } else {
                        out.append(c);
                    }
                }
            }
        }
        return out.append('"').toString();
    }

    /// The package documentation for the generated table.
    ///
    /// @return the generated file
    GeneratedFile packageInfo() {
        String content = """
                /// Mapping rows compiled from the declarations in
                /// `zengin4j-iso20022/mappings/`.
                ///
                /// GENERATED — do not edit. Change a declaration and run
                /// `./gradlew generateFormatSources`.
                ///
                /// @since 0.5.0
                package io.zengin4j.iso20022.mapping.generated;
                """;
        return new GeneratedFile(
                javaOut.resolve(PACKAGE.replace('.', '/')).resolve("package-info.java"), content);
    }
}
