package io.zengin4j.codegen;

import io.zengin4j.core.format.FieldDescriptor;
import io.zengin4j.core.format.FieldFormat;
import io.zengin4j.core.format.FormatDescriptor;
import io.zengin4j.core.format.RecordDescriptor;
import io.zengin4j.core.format.RecordKind;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;

/**
 * Emits the committed, format-shaped record classes (R-F3, R-M8).
 *
 * <p>Generation rather than hand-writing is not a convenience. A record class
 * written by hand can disagree with the descriptor it claims to implement, and
 * the disagreement is a wrong byte offset in a payment file. Generated code
 * cannot disagree, and the build fails if the committed output has drifted
 * from the descriptors.
 */
final class RecordSourceGenerator {

    static final String PACKAGE = "io.zengin4j.core.model.generated";
    static final String GENERATOR = "io.zengin4j.codegen.RecordSourceGenerator";

    private static final String NL = "\n";
    private static final Set<String> ALWAYS_RESERVED =
            Set.of("formatId", "kind", "rawBytes", "recordNumber", "byteOffset");

    private final Path javaRoot;

    RecordSourceGenerator(Path javaRoot) {
        this.javaRoot = javaRoot;
    }

    List<GeneratedFile> generate(FormatDescriptor format, String source) {
        List<GeneratedFile> files = new ArrayList<>();
        for (RecordKind kind : orderedKinds(format)) {
            RecordDescriptor record = format.record(kind);
            validate(format, record);
            files.add(file(Names.typeName(format.id(), kind), recordClass(format, record, source)));
        }
        files.add(file(Names.factoryTypeName(format.id()), factoryClass(format, source)));
        return files;
    }

    GeneratedFile aggregate(List<FormatDescriptor> formats) {
        StringBuilder out = new StringBuilder();
        header(out, "io.zengin4j.core.annotation.Generated", "io.zengin4j.core.codec.RecordFactory",
                "io.zengin4j.core.format.FieldDescriptor", "io.zengin4j.core.format.FormatId",
                "io.zengin4j.core.format.RecordDescriptor",
                "java.util.List", "java.util.Map", "java.util.Optional", "java.util.Set");
        out.append("/**").append(NL)
                .append(" * Index of the generated, format-shaped record factories.").append(NL)
                .append(" *").append(NL)
                .append(" * <p>GENERATED by ").append(GENERATOR).append(" — do not edit.").append(NL)
                .append(" *").append(NL)
                .append(" * @since 0.1.0").append(NL)
                .append(" */").append(NL)
                .append("@Generated(value = \"").append(GENERATOR).append("\", source = \"all descriptors\")")
                .append(NL)
                .append("public final class GeneratedRecords {").append(NL).append(NL)
                .append("    private static final Map<FormatId, RecordFactory> FACTORIES = Map.of(")
                .append(formats.isEmpty() ? ");" : "")
                .append(NL);
        for (int i = 0; i < formats.size(); i++) {
            FormatDescriptor format = formats.get(i);
            out.append("            ").append(Names.typeName(format.id(), RecordKind.HEADER))
                    .append(".FORMAT_ID, ").append(Names.factoryTypeName(format.id())).append(".INSTANCE")
                    .append(i == formats.size() - 1 ? ");" : ",").append(NL);
        }
        out.append(NL)
                .append("    private GeneratedRecords() {").append(NL)
                .append("    }").append(NL).append(NL)
                .append("    /**").append(NL)
                .append("     * Returns the factory that materialises records of a format.").append(NL)
                .append("     *").append(NL)
                .append("     * @param id the format id").append(NL)
                .append("     * @return the factory, or empty for a format with no generated code")
                .append(NL)
                .append("     */").append(NL)
                .append("    public static Optional<RecordFactory> forFormat(FormatId id) {").append(NL)
                .append("        return Optional.ofNullable(FACTORIES.get(id));").append(NL)
                .append("    }").append(NL).append(NL)
                .append("    /**").append(NL)
                .append("     * Returns every format that has generated record types.").append(NL)
                .append("     *").append(NL)
                .append("     * @return an unmodifiable set of format ids").append(NL)
                .append("     */").append(NL)
                .append("    public static Set<FormatId> formats() {").append(NL)
                .append("        return FACTORIES.keySet();").append(NL)
                .append("    }").append(NL).append(NL)
                .append("    /**").append(NL)
                .append("     * Resolves a field by position, verifying its id, and falls back to a")
                .append(NL)
                .append("     * lookup by id if a caller supplied a descriptor that differs from the")
                .append(NL)
                .append("     * one this code was generated from.").append(NL)
                .append("     */").append(NL)
                .append("    static FieldDescriptor field(RecordDescriptor record, int index, String id) {")
                .append(NL)
                .append("        List<FieldDescriptor> fields = record.fields();").append(NL)
                .append("        if (index < fields.size()) {").append(NL)
                .append("            FieldDescriptor candidate = fields.get(index);").append(NL)
                .append("            if (candidate.id().equals(id)) {").append(NL)
                .append("                return candidate;").append(NL)
                .append("            }").append(NL)
                .append("        }").append(NL)
                .append("        return record.field(id);").append(NL)
                .append("    }").append(NL)
                .append("}").append(NL);
        return file("GeneratedRecords", out.toString());
    }

    GeneratedFile packageInfo() {
        String content = "/**" + NL
                + " * Record classes generated from the format descriptors (§13)." + NL
                + " *" + NL
                + " * <p>GENERATED and committed, never hand-edited (R-M8). The build regenerates" + NL
                + " * these files and fails if the committed output differs, so the only way to" + NL
                + " * change a byte layout is to change the descriptor it comes from." + NL
                + " *" + NL
                + " * <p>Each type carries exactly the fields its record carries, in the order the" + NL
                + " * record carries them (R-D1), plus the raw bytes so that filler and reserved" + NL
                + " * space survive a round trip verbatim (R-D5)." + NL
                + " *" + NL
                + " * @since 0.1.0" + NL
                + " */" + NL
                + "package " + PACKAGE + ";" + NL;
        return file("package-info", content);
    }

    // ------------------------------------------------------------ record class

    private String recordClass(FormatDescriptor format, RecordDescriptor record, String source) {
        String typeName = Names.typeName(format.id(), record.kind());
        List<FieldDescriptor> fields = record.fields();
        StringBuilder out = new StringBuilder();

        header(out, imports(format, record).toArray(String[]::new));

        out.append("/**").append(NL)
                .append(" * ").append(format.nameJa()).append(" (").append(format.nameEn()).append(") — ")
                .append(record.kind().descriptorKey()).append(" record, ")
                .append(record.recordLength()).append(" bytes.").append(NL)
                .append(" *").append(NL)
                .append(" * <p>GENERATED by ").append(GENERATOR).append(" from ").append(source)
                .append(" — do not edit.").append(NL);
        if (!format.verified()) {
            out.append(" *").append(NL)
                    .append(" * <p><strong>The byte offsets below are provisional.</strong> The descriptor")
                    .append(NL)
                    .append(" * this type was generated from is marked {@code verified: false}: its layout")
                    .append(NL)
                    .append(" * has not been confirmed against two independent published sources (R-0.1).")
                    .append(NL);
        }
        out.append(" *").append(NL);
        out.append(" * @param recordNumber the 1-based position of the record in the file").append(NL)
                .append(" * @param byteOffset   the record's byte offset within the file").append(NL)
                .append(" * @param rawBytes     the record's bytes, exactly as they appeared").append(NL);
        for (FieldDescriptor field : fields) {
            out.append(" * @param ").append(Names.componentName(field)).append(' ')
                    .append(field.nameJa()).append(" (").append(field.nameEn()).append("), ")
                    .append(field.type()).append('(').append(field.length()).append(") at byte ")
                    .append(field.offset()).append(NL);
        }
        out.append(" * @since 0.1.0").append(NL)
                .append(" */").append(NL)
                .append("@Generated(value = \"").append(GENERATOR).append("\", source = \"").append(source)
                .append("\")").append(NL)
                .append("public record ").append(typeName).append('(').append(NL)
                .append("        int recordNumber,").append(NL)
                .append("        long byteOffset,").append(NL)
                .append("        byte[] rawBytes");
        for (FieldDescriptor field : fields) {
            out.append(',').append(NL).append("        ").append(Names.componentType(field)).append(' ')
                    .append(Names.componentName(field));
        }
        out.append(") implements ").append(roleInterface(record.kind())).append(" {").append(NL).append(NL);

        constants(out, format, record);
        compactConstructor(out, typeName, fields);
        roleAccessors(out, format, record);
        equality(out, typeName);
        stringForm(out, typeName, fields);

        out.append('}').append(NL);
        return out.toString();
    }

    private void constants(StringBuilder out, FormatDescriptor format, RecordDescriptor record) {
        out.append("    /** The format these records belong to. */").append(NL)
                .append("    public static final FormatId FORMAT_ID = FormatId.of(\"")
                .append(format.id().value()).append("\");").append(NL).append(NL)
                .append("    /** Record length in bytes. */").append(NL)
                .append("    public static final int RECORD_LENGTH = ").append(record.recordLength())
                .append(';').append(NL).append(NL)
                .append("    /** データ区分 identifying this record kind. */").append(NL)
                .append("    public static final byte DISCRIMINATOR = '")
                .append((char) record.discriminator()).append("';").append(NL).append(NL);
        for (FieldDescriptor field : record.fields()) {
            String prefix = Names.constantPrefix(field);
            out.append("    /** Byte offset of ").append(field.nameJa()).append(". */").append(NL)
                    .append("    public static final int ").append(prefix).append("_OFFSET = ")
                    .append(field.offset()).append(';').append(NL)
                    .append("    /** Length in bytes of ").append(field.nameJa()).append(". */").append(NL)
                    .append("    public static final int ").append(prefix).append("_LENGTH = ")
                    .append(field.length()).append(';').append(NL).append(NL);
        }
    }

    private void compactConstructor(StringBuilder out, String typeName, List<FieldDescriptor> fields) {
        out.append("    /**").append(NL)
                .append("     * Copies the raw bytes defensively and rejects null components.").append(NL)
                .append("     */").append(NL)
                .append("    public ").append(typeName).append(" {").append(NL)
                .append("        rawBytes = Objects.requireNonNull(rawBytes, \"rawBytes\").clone();")
                .append(NL);
        for (FieldDescriptor field : fields) {
            if (Names.componentType(field).equals("String")) {
                String name = Names.componentName(field);
                out.append("        Objects.requireNonNull(").append(name).append(", \"").append(name)
                        .append("\");").append(NL);
            }
        }
        out.append("    }").append(NL).append(NL);
    }

    private void roleAccessors(StringBuilder out, FormatDescriptor format, RecordDescriptor record) {
        out.append("    @Override").append(NL)
                .append("    public FormatId formatId() {").append(NL)
                .append("        return FORMAT_ID;").append(NL)
                .append("    }").append(NL).append(NL)
                .append("    @Override").append(NL)
                .append("    public byte[] rawBytes() {").append(NL)
                .append("        return rawBytes.clone();").append(NL)
                .append("    }").append(NL).append(NL);

        switch (record.kind()) {
            case HEADER -> headerAccessors(out, record);
            case DATA -> delegate(out, record, FieldFormat.AMOUNT, "long", "amount", "0L");
            case TRAILER -> {
                delegate(out, record, FieldFormat.COUNT, "int", "recordCount", "0");
                delegate(out, record, FieldFormat.AMOUNT, "long", "totalAmount", "0L");
            }
            case END -> out.append("    @Override").append(NL)
                    .append("    public byte[] filler() {").append(NL)
                    .append("        return Arrays.copyOfRange(rawBytes, 1, rawBytes.length);").append(NL)
                    .append("    }").append(NL).append(NL);
            case MALFORMED -> throw new CodegenException("MALFORMED is not a declarable record kind");
        }
    }

    private void headerAccessors(StringBuilder out, RecordDescriptor record) {
        Optional<FieldDescriptor> codeKubun = record.findByFormat(FieldFormat.CODE_KUBUN);
        out.append("    @Override").append(NL)
                .append("    public CodeKubun codeKubun() {").append(NL)
                .append("        return ")
                .append(codeKubun.map(field -> "CodeKubun.of(" + Names.componentName(field) + ")")
                        .orElse("CodeKubun.UNKNOWN"))
                .append(';').append(NL)
                .append("    }").append(NL).append(NL);

        Optional<FieldDescriptor> valueDate = record.findByFormat(FieldFormat.MMDD);
        out.append("    @Override").append(NL)
                .append("    public Optional<MonthDay> valueDate() {").append(NL)
                .append("        return ")
                .append(valueDate.map(field -> "MonthDays.parse(" + Names.componentName(field) + ")")
                        .orElse("Optional.empty()"))
                .append(';').append(NL)
                .append("    }").append(NL).append(NL);

        textAccessor(out, record, "originatorCode");
        textAccessor(out, record, "originatorName");
    }

    private void textAccessor(StringBuilder out, RecordDescriptor record, String accessor) {
        if (record.find(accessor).isPresent()) {
            // The record component of the same name already satisfies the role.
            return;
        }
        out.append("    @Override").append(NL)
                .append("    public String ").append(accessor).append("() {").append(NL)
                .append("        return \"\";").append(NL)
                .append("    }").append(NL).append(NL);
    }

    private void delegate(
            StringBuilder out, RecordDescriptor record, FieldFormat format,
            String type, String accessor, String absent) {
        Optional<FieldDescriptor> field = record.findByFormat(format);
        if (field.isPresent() && field.get().id().equals(accessor)) {
            return;
        }
        out.append("    @Override").append(NL)
                .append("    public ").append(type).append(' ').append(accessor).append("() {").append(NL)
                .append("        return ").append(field.map(FieldDescriptor::id).orElse(absent)).append(';')
                .append(NL)
                .append("    }").append(NL).append(NL);
    }

    private void equality(StringBuilder out, String typeName) {
        out.append("    /**").append(NL)
                .append("     * Two records are equal when they are the same kind and carry the same")
                .append(NL)
                .append("     * bytes. The decoded components are derived from those bytes, and the")
                .append(NL)
                .append("     * record number and byte offset are metadata about where the record was")
                .append(NL)
                .append("     * found rather than part of what it is.").append(NL)
                .append("     *").append(NL)
                .append("     * @param other the object to compare with").append(NL)
                .append("     * @return whether the records are equal").append(NL)
                .append("     */").append(NL)
                .append("    @Override").append(NL)
                .append("    public boolean equals(Object other) {").append(NL)
                .append("        return other instanceof ").append(typeName)
                .append(" record && Arrays.equals(rawBytes, record.rawBytes);").append(NL)
                .append("    }").append(NL).append(NL)
                .append("    @Override").append(NL)
                .append("    public int hashCode() {").append(NL)
                .append("        return Arrays.hashCode(rawBytes);").append(NL)
                .append("    }").append(NL).append(NL);
    }

    private void stringForm(StringBuilder out, String typeName, List<FieldDescriptor> fields) {
        out.append("    /**").append(NL)
                .append("     * Renders the record with account numbers masked to their last four")
                .append(NL)
                .append("     * digits (R-E6). Full values are available from the accessors, which is")
                .append(NL)
                .append("     * the explicit opt-in.").append(NL)
                .append("     *").append(NL)
                .append("     * @return a diagnostic description").append(NL)
                .append("     */").append(NL)
                .append("    @Override").append(NL)
                .append("    public String toString() {").append(NL)
                .append("        return \"").append(typeName).append("[recordNumber=\" + recordNumber");
        for (FieldDescriptor field : fields) {
            if (field.filler()) {
                continue;
            }
            String name = Names.componentName(field);
            String value = field.sensitive()
                    ? "Diagnostics.maskIdentifier(String.valueOf(" + name + "))"
                    : name;
            out.append(NL).append("                + \", ").append(name).append("=\" + ").append(value);
        }
        out.append(NL).append("                + \"]\";").append(NL)
                .append("    }").append(NL).append(NL);
    }

    // ----------------------------------------------------------- factory class

    private String factoryClass(FormatDescriptor format, String source) {
        String typeName = Names.factoryTypeName(format.id());
        StringBuilder out = new StringBuilder();
        Set<String> imports = new TreeSet<>(Set.of(
                "io.zengin4j.core.annotation.Generated",
                "io.zengin4j.core.codec.RecordFactory",
                "io.zengin4j.core.codec.RecordView",
                "io.zengin4j.core.format.RecordDescriptor",
                "io.zengin4j.core.model.ZenginRecord"));
        header(out, imports.toArray(String[]::new));

        out.append("/**").append(NL)
                .append(" * Materialises ").append(format.nameJa()).append(" records.").append(NL)
                .append(" *").append(NL)
                .append(" * <p>GENERATED by ").append(GENERATOR).append(" from ").append(source)
                .append(" — do not edit.").append(NL)
                .append(" */").append(NL)
                .append("@Generated(value = \"").append(GENERATOR).append("\", source = \"").append(source)
                .append("\")").append(NL)
                .append("final class ").append(typeName).append(" implements RecordFactory {").append(NL)
                .append(NL)
                .append("    static final ").append(typeName).append(" INSTANCE = new ").append(typeName)
                .append("();").append(NL).append(NL)
                .append("    private ").append(typeName).append("() {").append(NL)
                .append("    }").append(NL).append(NL)
                .append("    @Override").append(NL)
                .append("    public ZenginRecord materialize(RecordView view) {").append(NL)
                .append("        RecordDescriptor record = view.requireDescriptor();").append(NL)
                .append("        return switch (record.kind()) {").append(NL);
        for (RecordKind kind : orderedKinds(format)) {
            out.append("            case ").append(kind).append(" -> ")
                    .append(builderMethodName(kind)).append("(view, record);").append(NL);
        }
        for (RecordKind kind : RecordKind.values()) {
            if (kind != RecordKind.MALFORMED && format.find(kind).isEmpty()) {
                out.append("            case ").append(kind)
                        .append(" -> throw new IllegalStateException(\"format ").append(format.id())
                        .append(" declares no ").append(kind).append(" record\");").append(NL);
            }
        }
        out.append("            case MALFORMED -> throw new IllegalStateException(")
                .append("\"a malformed record has no descriptor\");").append(NL)
                .append("        };").append(NL)
                .append("    }").append(NL).append(NL);

        for (RecordKind kind : orderedKinds(format)) {
            RecordDescriptor record = format.record(kind);
            out.append("    private static ").append(Names.typeName(format.id(), kind)).append(' ')
                    .append(builderMethodName(kind)).append("(RecordView view, RecordDescriptor record) {")
                    .append(NL)
                    .append("        return new ").append(Names.typeName(format.id(), kind)).append('(')
                    .append(NL)
                    .append("                view.recordNumber(),").append(NL)
                    .append("                view.byteOffset(),").append(NL)
                    .append("                view.rawBytes()");
            List<FieldDescriptor> fields = record.fields();
            for (int i = 0; i < fields.size(); i++) {
                FieldDescriptor field = fields.get(i);
                out.append(',').append(NL).append("                ")
                        .append(accessorCall(field, i));
            }
            out.append(");").append(NL)
                    .append("    }").append(NL).append(NL);
        }
        out.append('}').append(NL);
        return out.toString();
    }

    private String accessorCall(FieldDescriptor field, int index) {
        String lookup = "GeneratedRecords.field(record, " + index + ", \"" + field.id() + "\")";
        if (field.hasFormat(FieldFormat.AMOUNT)) {
            return "view.asLong(" + lookup + ")";
        }
        if (field.hasFormat(FieldFormat.COUNT)) {
            return "Math.toIntExact(view.asLong(" + lookup + "))";
        }
        if (Names.keepsRawComponent(field)) {
            return "view.asPaddedString(" + lookup + ")";
        }
        return "view.asString(" + lookup + ")";
    }

    private static String builderMethodName(RecordKind kind) {
        return kind.name().toLowerCase(java.util.Locale.ROOT);
    }

    // ---------------------------------------------------------------- helpers

    private static List<RecordKind> orderedKinds(FormatDescriptor format) {
        List<RecordKind> kinds = new ArrayList<>();
        for (RecordKind kind : List.of(RecordKind.HEADER, RecordKind.DATA, RecordKind.TRAILER, RecordKind.END)) {
            if (format.find(kind).isPresent()) {
                kinds.add(kind);
            }
        }
        return kinds;
    }

    private static String roleInterface(RecordKind kind) {
        return switch (kind) {
            case HEADER -> "HeaderRecord";
            case DATA -> "DataRecord";
            case TRAILER -> "TrailerRecord";
            case END -> "EndRecord";
            case MALFORMED -> throw new CodegenException("MALFORMED is not a declarable record kind");
        };
    }

    private static Set<String> imports(FormatDescriptor format, RecordDescriptor record) {
        Set<String> imports = new TreeSet<>();
        imports.add("io.zengin4j.core.annotation.Generated");
        imports.add("io.zengin4j.core.format.FormatId");
        imports.add("io.zengin4j.core.model." + roleInterface(record.kind()));
        imports.add("java.util.Arrays");
        imports.add("java.util.Objects");
        if (record.kind() == RecordKind.HEADER) {
            imports.add("io.zengin4j.core.charset.CodeKubun");
            imports.add("java.time.MonthDay");
            imports.add("java.util.Optional");
            if (record.findByFormat(FieldFormat.MMDD).isPresent()) {
                imports.add("io.zengin4j.core.time.MonthDays");
            }
        }
        if (record.fields().stream().anyMatch(FieldDescriptor::sensitive)) {
            imports.add("io.zengin4j.core.error.Diagnostics");
        }
        return imports;
    }

    private void header(StringBuilder out, String... imports) {
        out.append("package ").append(PACKAGE).append(';').append(NL).append(NL);
        Set<String> sorted = new TreeSet<>(List.of(imports));
        for (String each : sorted) {
            out.append("import ").append(each).append(';').append(NL);
        }
        out.append(NL);
    }

    private GeneratedFile file(String simpleName, String content) {
        Path path = javaRoot;
        for (String part : PACKAGE.split("\\.")) {
            path = path.resolve(part);
        }
        return new GeneratedFile(path.resolve(simpleName + ".java"), content);
    }

    private static void validate(FormatDescriptor format, RecordDescriptor record) {
        Set<String> reserved = new HashSet<>(ALWAYS_RESERVED);
        switch (record.kind()) {
            case HEADER -> reserved.addAll(Set.of("codeKubun", "valueDate"));
            case END -> reserved.add("filler");
            default -> {
                // no additional reservations
            }
        }
        for (FieldDescriptor field : record.fields()) {
            String component = Names.componentName(field);
            if (reserved.contains(component)) {
                throw new CodegenException("format " + format.id() + ", record "
                        + record.kind().descriptorKey() + ": field id '" + field.id()
                        + "' collides with an accessor the record role already defines."
                        + " Rename the field, or declare the interpretation that gives it a raw"
                        + " component (format: MMDD or format: CODE-KUBUN).");
            }
        }
        switch (record.kind()) {
            case DATA -> requireFormat(format, record, FieldFormat.AMOUNT, "DataRecord.amount()");
            case TRAILER -> {
                requireFormat(format, record, FieldFormat.COUNT, "TrailerRecord.recordCount()");
                requireFormat(format, record, FieldFormat.AMOUNT, "TrailerRecord.totalAmount()");
            }
            default -> {
                // header and end have no field a descriptor must supply
            }
        }
        switch (record.kind()) {
            case HEADER -> {
                requireType(format, record, "originatorCode", "String");
                requireType(format, record, "originatorName", "String");
            }
            case DATA -> requireType(format, record, "amount", "long");
            case TRAILER -> {
                requireType(format, record, "recordCount", "int");
                requireType(format, record, "totalAmount", "long");
            }
            default -> {
                // end records carry no typed role accessors
            }
        }
    }

    private static void requireFormat(
            FormatDescriptor format, RecordDescriptor record, FieldFormat required, String accessor) {
        if (record.findByFormat(required).isEmpty()) {
            throw new CodegenException("format " + format.id() + ", record "
                    + record.kind().descriptorKey() + ": no field declares format: "
                    + required.descriptorValue() + ", so " + accessor + " cannot be generated."
                    + " Add the attribute to the field that carries it.");
        }
    }

    private static void requireType(
            FormatDescriptor format, RecordDescriptor record, String fieldId, String expectedType) {
        record.find(fieldId).ifPresent(field -> {
            String actual = Names.componentType(field);
            if (!actual.equals(expectedType)) {
                throw new CodegenException("format " + format.id() + ", record "
                        + record.kind().descriptorKey() + ": field '" + fieldId + "' would generate a "
                        + actual + " accessor, but the record role requires " + expectedType + '.');
            }
        });
    }
}
