package io.zengin4j.codegen;

import module java.base;
import io.zengin4j.core.format.FieldDescriptor;
import io.zengin4j.core.format.FieldFormat;
import io.zengin4j.core.format.FormatDescriptor;
import io.zengin4j.core.format.RecordDescriptor;
import io.zengin4j.core.format.RecordKind;

/// Emits the committed, format-shaped record classes (R-F3, R-M8).
///
/// Generation rather than hand-writing is not a convenience. A record class
/// written by hand can disagree with the descriptor it claims to implement, and
/// the disagreement is a wrong byte offset in a payment file. Generated code
/// cannot disagree, and the build fails if the committed output has drifted
/// from the descriptors.
final class RecordSourceGenerator {

    static final String PACKAGE = "io.zengin4j.core.model.generated";
    static final String GENERATOR = "io.zengin4j.codegen.RecordSourceGenerator";

    private static final String NL = "\n";
    private static final Set<String> ALWAYS_RESERVED =
            Set.of("formatId", "kind", "rawBytes", "recordNumber", "byteOffset");

    private final Path javaRoot;

    RecordSourceGenerator(Path javaRoot) {
        this.javaRoot = javaRoot;
    }

    List<GeneratedFile> generate(FormatDescriptor format, String source) {
        List<GeneratedFile> files = new ArrayList<>();
        for (RecordKind kind : orderedKinds(format)) {
            RecordDescriptor record = format.record(kind);
            validate(format, record);
            files.add(file(Names.typeName(format.id(), kind), recordClass(format, record, source)));
        }
        files.add(file(Names.factoryTypeName(format.id()), factoryClass(format, source)));
        return files;
    }

    GeneratedFile aggregate(List<FormatDescriptor> formats) {
        var out = new StringBuilder();
        header(out, "io.zengin4j.core.annotation.Generated", "io.zengin4j.core.codec.RecordFactory",
                "io.zengin4j.core.format.FieldDescriptor", "io.zengin4j.core.format.FormatId",
                "io.zengin4j.core.format.RecordDescriptor",
                "java.util.List", "java.util.Map", "java.util.Optional", "java.util.Set");
        out.append("""
                /// Index of the generated, format-shaped record factories.
                ///
                /// GENERATED by %s — do not edit.
                ///
                /// @since 0.1.0
                @Generated(value = "%s", source = "all descriptors")
                public final class GeneratedRecords {

                    private static final Map<FormatId, RecordFactory> FACTORIES = Map.of(%s
                """.formatted(GENERATOR, GENERATOR, formats.isEmpty() ? ");" : ""));
        for (int i = 0; i < formats.size(); i++) {
            FormatDescriptor format = formats.get(i);
            out.append("            ").append(Names.typeName(format.id(), RecordKind.HEADER))
                    .append(".FORMAT_ID, ").append(Names.factoryTypeName(format.id())).append(".INSTANCE")
                    .append(i == formats.size() - 1 ? ");" : ",").append(NL);
        }
        out.append("""

                    private GeneratedRecords() {
                    }

                    /// Returns the factory that materialises records of a format.
                    ///
                    /// @param id the format id
                    /// @return the factory, or empty for a format with no generated code
                    public static Optional<RecordFactory> forFormat(FormatId id) {
                        return Optional.ofNullable(FACTORIES.get(id));
                    }

                    /// Returns every format that has generated record types.
                    ///
                    /// @return an unmodifiable set of format ids
                    public static Set<FormatId> formats() {
                        return FACTORIES.keySet();
                    }

                    /// Resolves a field by position, verifying its id, and falls back to a
                    /// lookup by id if a caller supplied a descriptor that differs from the
                    /// one this code was generated from.
                    static FieldDescriptor field(RecordDescriptor record, int index, String id) {
                        List<FieldDescriptor> fields = record.fields();
                        if (index < fields.size()) {
                            FieldDescriptor candidate = fields.get(index);
                            if (candidate.id().equals(id)) {
                                return candidate;
                            }
                        }
                        return record.field(id);
                    }
                }
                """);
        return file("GeneratedRecords", out.toString());
    }

    GeneratedFile packageInfo() {
        String content = """
                /// Record classes generated from the format descriptors (§13).
                ///
                /// GENERATED and committed, never hand-edited (R-M8). The build regenerates
                /// these files and fails if the committed output differs, so the only way to
                /// change a byte layout is to change the descriptor it comes from.
                ///
                /// Each type carries exactly the fields its record carries, in the order the
                /// record carries them (R-D1), plus the raw bytes so that filler and reserved
                /// space survive a round trip verbatim (R-D5).
                ///
                /// @since 0.1.0
                package %s;
                """.formatted(PACKAGE);
        return file("package-info", content);
    }

    // ------------------------------------------------------------ record class

    private String recordClass(FormatDescriptor format, RecordDescriptor record, String source) {
        String typeName = Names.typeName(format.id(), record.kind());
        List<FieldDescriptor> fields = record.fields();
        var out = new StringBuilder();

        header(out, imports(format, record).toArray(String[]::new));

        out.append("/// ").append(format.nameJa()).append(" (").append(format.nameEn()).append(") — ")
                .append(record.kind().descriptorKey()).append(" record, ")
                .append(record.recordLength()).append(" bytes.").append(NL)
                .append("///").append(NL)
                .append("/// GENERATED by ").append(GENERATOR).append(" from ").append(source)
                .append(" — do not edit.").append(NL);
        if (!format.verified()) {
            out.append("///").append(NL)
                    .append("/// **The byte offsets below are provisional.** The descriptor")
                    .append(NL)
                    .append("/// this type was generated from is marked `verified: false`: its layout")
                    .append(NL)
                    .append("/// has not been confirmed against two independent published sources (R-0.1).")
                    .append(NL);
        }
        out.append("///").append(NL);
        out.append("/// @param recordNumber the 1-based position of the record in the file").append(NL)
                .append("/// @param byteOffset   the record's byte offset within the file").append(NL)
                .append("/// @param rawBytes     the record's bytes, exactly as they appeared").append(NL);
        for (FieldDescriptor field : fields) {
            out.append("/// @param ").append(Names.componentName(field)).append(' ')
                    .append(field.nameJa()).append(" (").append(field.nameEn()).append("), ")
                    .append(field.type()).append('(').append(field.length()).append(") at byte ")
                    .append(field.offset()).append(NL);
        }
        out.append("/// @since 0.1.0").append(NL)
                .append("@Generated(value = \"").append(GENERATOR).append("\", source = \"").append(source)
                .append("\")").append(NL)
                .append("public record ").append(typeName).append('(').append(NL)
                .append("        int recordNumber,").append(NL)
                .append("        long byteOffset,").append(NL)
                .append("        byte[] rawBytes");
        for (FieldDescriptor field : fields) {
            out.append(',').append(NL).append("        ").append(Names.componentType(field)).append(' ')
                    .append(Names.componentName(field));
        }
        out.append(") implements ").append(roleInterface(record.kind())).append(" {").append(NL).append(NL);

        constants(out, format, record);
        compactConstructor(out, typeName, fields);
        roleAccessors(out, format, record);
        equality(out, typeName);
        stringForm(out, typeName, fields);

        out.append('}').append(NL);
        return out.toString();
    }

    private void constants(StringBuilder out, FormatDescriptor format, RecordDescriptor record) {
        out.append("""
                    /// The format these records belong to.
                    public static final FormatId FORMAT_ID = FormatId.of("%s");

                    /// Record length in bytes.
                    public static final int RECORD_LENGTH = %d;

                    /// データ区分 identifying this record kind.
                    public static final byte DISCRIMINATOR = '%s';

                """.formatted(format.id().value(), record.recordLength(),
                        (char) record.discriminator()));
        for (FieldDescriptor field : record.fields()) {
            String prefix = Names.constantPrefix(field);
            out.append("    /// Byte offset of ").append(field.nameJa()).append(".").append(NL)
                    .append("    public static final int ").append(prefix).append("_OFFSET = ")
                    .append(field.offset()).append(';').append(NL)
                    .append("    /// Length in bytes of ").append(field.nameJa()).append(".").append(NL)
                    .append("    public static final int ").append(prefix).append("_LENGTH = ")
                    .append(field.length()).append(';').append(NL).append(NL);
        }
    }

    private void compactConstructor(StringBuilder out, String typeName, List<FieldDescriptor> fields) {
        out.append("    /// Copies the raw bytes defensively and rejects null components.").append(NL)
                .append("    public ").append(typeName).append(" {").append(NL)
                .append("        rawBytes = Objects.requireNonNull(rawBytes, \"rawBytes\").clone();")
                .append(NL);
        for (FieldDescriptor field : fields) {
            if (Names.componentType(field).equals("String")) {
                String name = Names.componentName(field);
                out.append("        Objects.requireNonNull(").append(name).append(", \"").append(name)
                        .append("\");").append(NL);
            }
        }
        out.append("    }").append(NL).append(NL);
    }

    private void roleAccessors(StringBuilder out, FormatDescriptor format, RecordDescriptor record) {
        out.append("""
                    @Override
                    public FormatId formatId() {
                        return FORMAT_ID;
                    }

                    @Override
                    public byte[] rawBytes() {
                        return rawBytes.clone();
                    }

                """);

        switch (record.kind()) {
            case HEADER -> headerAccessors(out, record);
            case DATA -> delegate(out, record, FieldFormat.AMOUNT, "long", "amount", "0L");
            case TRAILER -> {
                delegate(out, record, FieldFormat.COUNT, "int", "recordCount", "0");
                delegate(out, record, FieldFormat.AMOUNT, "long", "totalAmount", "0L");
            }
            case END -> out.append("""
                        @Override
                        public byte[] filler() {
                            return Arrays.copyOfRange(rawBytes, 1, rawBytes.length);
                        }

                    """);
            case MALFORMED -> throw new CodegenException("MALFORMED is not a declarable record kind");
        }
    }

    private void headerAccessors(StringBuilder out, RecordDescriptor record) {
        Optional<FieldDescriptor> codeKubun = record.findByFormat(FieldFormat.CODE_KUBUN);
        out.append("    @Override").append(NL)
                .append("    public CodeKubun codeKubun() {").append(NL)
                .append("        return ")
                .append(codeKubun.map(field -> "CodeKubun.of(" + Names.componentName(field) + ")")
                        .orElse("CodeKubun.UNKNOWN"))
                .append(';').append(NL)
                .append("    }").append(NL).append(NL);

        Optional<FieldDescriptor> dated = record.findByFormat(FieldFormat.MMDD);
        out.append("    @Override").append(NL)
                .append("    public Optional<MonthDay> effectiveDate() {").append(NL)
                .append("        return ")
                .append(dated.map(field -> "MonthDays.parse(" + Names.componentName(field) + ")")
                        .orElse("Optional.empty()"))
                .append(';').append(NL)
                .append("    }").append(NL).append(NL);

        // And the same date under the name this format actually uses, so code
        // written against a concrete record reads in its own terms (R-D1, OQ-6).
        dated.ifPresent(field -> out.append("""
                    /// Returns %s (%s) as a month and day.
                    ///
                    /// @return the month and day, or empty if unset or not a valid date
                    public Optional<MonthDay> %s() {
                        return effectiveDate();
                    }

                """.formatted(field.nameJa(), field.nameEn(), field.id())));

        textAccessor(out, record, "originatorCode");
        textAccessor(out, record, "originatorName");
    }

    private void textAccessor(StringBuilder out, RecordDescriptor record, String accessor) {
        if (record.find(accessor).isPresent()) {
            // The record component of the same name already satisfies the role.
            return;
        }
        out.append("""
                    @Override
                    public String %s() {
                        return "";
                    }

                """.formatted(accessor));
    }

    private void delegate(
            StringBuilder out, RecordDescriptor record, FieldFormat format,
            String type, String accessor, String absent) {
        Optional<FieldDescriptor> field = record.findByFormat(format);
        if (field.isPresent() && field.get().id().equals(accessor)) {
            return;
        }
        out.append("""
                    @Override
                    public %s %s() {
                        return %s;
                    }

                """.formatted(type, accessor, field.map(FieldDescriptor::id).orElse(absent)));
    }

    private void equality(StringBuilder out, String typeName) {
        out.append("""
                    /// Two records are equal when they are the same kind and carry the same
                    /// bytes. The decoded components are derived from those bytes, and the
                    /// record number and byte offset are metadata about where the record was
                    /// found rather than part of what it is.
                    ///
                    /// @param other the object to compare with
                    /// @return whether the records are equal
                    @Override
                    public boolean equals(Object other) {
                        return other instanceof %s record && Arrays.equals(rawBytes, record.rawBytes);
                    }

                    @Override
                    public int hashCode() {
                        return Arrays.hashCode(rawBytes);
                    }

                """.formatted(typeName));
    }

    private void stringForm(StringBuilder out, String typeName, List<FieldDescriptor> fields) {
        out.append("""
                    /// Renders the record with account numbers masked to their last four
                    /// digits (R-E6). Full values are available from the accessors, which is
                    /// the explicit opt-in.
                    ///
                    /// @return a diagnostic description
                    @Override
                    public String toString() {
                        return "%s[recordNumber=" + recordNumber\
                """.formatted(typeName));
        for (FieldDescriptor field : fields) {
            if (field.filler()) {
                continue;
            }
            String name = Names.componentName(field);
            String value = field.sensitive()
                    ? "Diagnostics.maskIdentifier(String.valueOf(" + name + "))"
                    : name;
            out.append(NL).append("                + \", ").append(name).append("=\" + ").append(value);
        }
        out.append(NL).append("                + \"]\";").append(NL)
                .append("    }").append(NL).append(NL);
    }

    // ----------------------------------------------------------- factory class

    private String factoryClass(FormatDescriptor format, String source) {
        String typeName = Names.factoryTypeName(format.id());
        var out = new StringBuilder();
        Set<String> imports = new TreeSet<>(Set.of(
                "io.zengin4j.core.annotation.Generated",
                "io.zengin4j.core.codec.RecordFactory",
                "io.zengin4j.core.codec.RecordView",
                "io.zengin4j.core.format.RecordDescriptor",
                "io.zengin4j.core.model.ZenginRecord"));
        header(out, imports.toArray(String[]::new));

        out.append("""
                /// Materialises %s records.
                ///
                /// GENERATED by %s from %s — do not edit.
                @Generated(value = "%s", source = "%s")
                final class %s implements RecordFactory {

                    static final %s INSTANCE = new %s();

                    private %s() {
                    }

                    @Override
                    public ZenginRecord materialize(RecordView view) {
                        RecordDescriptor record = view.requireDescriptor();
                        return switch (record.kind()) {
                """.formatted(format.nameJa(), GENERATOR, source, GENERATOR, source,
                        typeName, typeName, typeName, typeName));
        for (RecordKind kind : orderedKinds(format)) {
            out.append("            case ").append(kind).append(" -> ")
                    .append(builderMethodName(kind)).append("(view, record);").append(NL);
        }
        for (RecordKind kind : RecordKind.values()) {
            if (kind != RecordKind.MALFORMED && format.find(kind).isEmpty()) {
                out.append("            case ").append(kind)
                        .append(" -> throw new IllegalStateException(\"format ").append(format.id())
                        .append(" declares no ").append(kind).append(" record\");").append(NL);
            }
        }
        out.append("""
                            case MALFORMED -> throw new IllegalStateException("a malformed record has no descriptor");
                        };
                    }

                """);

        for (RecordKind kind : orderedKinds(format)) {
            RecordDescriptor record = format.record(kind);
            out.append("""
                        private static %s %s(RecordView view, RecordDescriptor record) {
                            return new %s(
                                    view.recordNumber(),
                                    view.byteOffset(),
                                    view.rawBytes()\
                    """.formatted(Names.typeName(format.id(), kind), builderMethodName(kind),
                            Names.typeName(format.id(), kind)));
            List<FieldDescriptor> fields = record.fields();
            for (int i = 0; i < fields.size(); i++) {
                FieldDescriptor field = fields.get(i);
                out.append(',').append(NL).append("                ")
                        .append(accessorCall(field, i));
            }
            out.append(");").append(NL)
                    .append("    }").append(NL).append(NL);
        }
        out.append('}').append(NL);
        return out.toString();
    }

    private String accessorCall(FieldDescriptor field, int index) {
        String lookup = "GeneratedRecords.field(record, " + index + ", \"" + field.id() + "\")";
        if (field.hasFormat(FieldFormat.AMOUNT)) {
            return "view.asLong(" + lookup + ")";
        }
        if (field.hasFormat(FieldFormat.COUNT)) {
            return "Math.toIntExact(view.asLong(" + lookup + "))";
        }
        if (Names.keepsRawComponent(field)) {
            return "view.asPaddedString(" + lookup + ")";
        }
        return "view.asString(" + lookup + ")";
    }

    private static String builderMethodName(RecordKind kind) {
        return kind.name().toLowerCase(java.util.Locale.ROOT);
    }

    // ---------------------------------------------------------------- helpers

    private static List<RecordKind> orderedKinds(FormatDescriptor format) {
        List<RecordKind> kinds = new ArrayList<>();
        for (RecordKind kind : List.of(RecordKind.HEADER, RecordKind.DATA, RecordKind.TRAILER, RecordKind.END)) {
            if (format.find(kind).isPresent()) {
                kinds.add(kind);
            }
        }
        return kinds;
    }

    private static String roleInterface(RecordKind kind) {
        return switch (kind) {
            case HEADER -> "HeaderRecord";
            case DATA -> "DataRecord";
            case TRAILER -> "TrailerRecord";
            case END -> "EndRecord";
            case MALFORMED -> throw new CodegenException("MALFORMED is not a declarable record kind");
        };
    }

    private static Set<String> imports(FormatDescriptor format, RecordDescriptor record) {
        Set<String> imports = new TreeSet<>();
        imports.add("io.zengin4j.core.annotation.Generated");
        imports.add("io.zengin4j.core.format.FormatId");
        imports.add("io.zengin4j.core.model." + roleInterface(record.kind()));
        imports.add("java.util.Arrays");
        imports.add("java.util.Objects");
        if (record.kind() == RecordKind.HEADER) {
            imports.add("io.zengin4j.core.charset.CodeKubun");
            imports.add("java.time.MonthDay");
            imports.add("java.util.Optional");
            if (record.findByFormat(FieldFormat.MMDD).isPresent()) {
                imports.add("io.zengin4j.core.time.MonthDays");
            }
        }
        if (record.fields().stream().anyMatch(FieldDescriptor::sensitive)) {
            imports.add("io.zengin4j.core.error.Diagnostics");
        }
        return imports;
    }

    /// Writes the package declaration and the import block.
    ///
    /// Everything the generated code uses from the JDK comes from `java.base`,
    /// so those imports collapse into a single module import — the same
    /// convention the hand-written sources follow.
    private void header(StringBuilder out, String... imports) {
        out.append("package ").append(PACKAGE).append(';').append(NL).append(NL);
        Set<String> sorted = new TreeSet<>(List.of(imports));
        if (sorted.removeIf(each -> each.startsWith("java."))) {
            out.append("import module java.base;").append(NL);
        }
        for (String each : sorted) {
            out.append("import ").append(each).append(';').append(NL);
        }
        out.append(NL);
    }

    private GeneratedFile file(String simpleName, String content) {
        Path path = javaRoot;
        for (String part : PACKAGE.split("\\.")) {
            path = path.resolve(part);
        }
        return new GeneratedFile(path.resolve(simpleName + ".java"), content);
    }

    /// What a record role obliges its descriptor to declare: a field carrying
    /// a given interpretation, and the accessor that would be generated from it.
    private record RequiredFormat(FieldFormat fieldFormat, String accessor) {
    }

    /// A component the record role's interface fixes the Java type of.
    private record RequiredType(String fieldId, String javaType) {
    }

    /// Checks a descriptor against what its record role promises.
    ///
    /// Each obligation is a switch **expression** over [RecordKind], not a
    /// switch statement. That is deliberate: only expressions are checked for
    /// exhaustiveness, so adding a record kind fails this file to compile
    /// rather than silently acquiring no obligations. MALFORMED is listed
    /// throughout because it is exactly the kind a record takes on when no
    /// descriptor matched it, so it never arrives here with one.
    ///
    /// @param format the format the record belongs to, for the diagnostic
    /// @param record the record being generated
    private static void validate(FormatDescriptor format, RecordDescriptor record) {
        Set<String> reserved = new HashSet<>(ALWAYS_RESERVED);
        reserved.addAll(switch (record.kind()) {
            case HEADER -> Set.of("codeKubun", "effectiveDate");
            case END -> Set.of("filler");
            case DATA, TRAILER, MALFORMED -> Set.of();
        });
        for (FieldDescriptor field : record.fields()) {
            String component = Names.componentName(field);
            if (reserved.contains(component)) {
                throw new CodegenException("format " + format.id() + ", record "
                        + record.kind().descriptorKey() + ": field id '" + field.id()
                        + "' collides with an accessor the record role already defines."
                        + " Rename the field, or declare the interpretation that gives it a raw"
                        + " component (format: MMDD or format: CODE-KUBUN).");
            }
        }
        List<RequiredFormat> formats = switch (record.kind()) {
            case DATA -> List.of(
                    new RequiredFormat(FieldFormat.AMOUNT, "DataRecord.amount()"));
            case TRAILER -> List.of(
                    new RequiredFormat(FieldFormat.COUNT, "TrailerRecord.recordCount()"),
                    new RequiredFormat(FieldFormat.AMOUNT, "TrailerRecord.totalAmount()"));
            // header and end have no field a descriptor must supply
            case HEADER, END, MALFORMED -> List.of();
        };
        for (RequiredFormat required : formats) {
            requireFormat(format, record, required.fieldFormat(), required.accessor());
        }

        List<RequiredType> types = switch (record.kind()) {
            case HEADER -> List.of(
                    new RequiredType("originatorCode", "String"),
                    new RequiredType("originatorName", "String"));
            case DATA -> List.of(new RequiredType("amount", "long"));
            case TRAILER -> List.of(
                    new RequiredType("recordCount", "int"),
                    new RequiredType("totalAmount", "long"));
            // end records carry no typed role accessors
            case END, MALFORMED -> List.of();
        };
        for (RequiredType required : types) {
            requireType(format, record, required.fieldId(), required.javaType());
        }
    }

    private static void requireFormat(
            FormatDescriptor format, RecordDescriptor record, FieldFormat required, String accessor) {
        if (record.findByFormat(required).isEmpty()) {
            throw new CodegenException("format " + format.id() + ", record "
                    + record.kind().descriptorKey() + ": no field declares format: "
                    + required.descriptorValue() + ", so " + accessor + " cannot be generated."
                    + " Add the attribute to the field that carries it.");
        }
    }

    private static void requireType(
            FormatDescriptor format, RecordDescriptor record, String fieldId, String expectedType) {
        record.find(fieldId).ifPresent(field -> {
            String actual = Names.componentType(field);
            if (!actual.equals(expectedType)) {
                throw new CodegenException("format " + format.id() + ", record "
                        + record.kind().descriptorKey() + ": field '" + fieldId + "' would generate a "
                        + actual + " accessor, but the record role requires " + expectedType + '.');
            }
        });
    }
}
